
services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGO_PORT}:27017"

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"


networks:
  default:
    driver: bridge