name: Load Test

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Artillery
      run: npm install -g artillery

    - name: Run Load Test
      run: artillery run backend/load-test.yml
